### Login with admin account
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
  "email": "Tranchinh@gmail.com",
  "password": "password123"
}

### Create new blog
POST http://localhost:4000/api/v1/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJUcmFuY2hpbmhAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4MzY0NzgxLCJleHAiOjE3NTgzNjY1ODF9.jJTKvw3bvA1lK_oBu1y-fAYdpuR-G8lR7WCyjG2wGis
Content-Type: application/json

{
  "title": "My First Blog",
  "content": "This is the content of my blog ddhshjdsjhjsdjsd...",
  "image_blogs": "https://example.com/image.jpg",
  "status": "active"
}

### Get all blogs
GET http://localhost:4000/api/v1/blogs/

### Get blog by id
GET http://localhost:4000/api/v1/blogs/2

### Update blog
PUT http://localhost:4000/api/v1/blogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJUcmFuY2hpbmhAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4MzY0NzgxLCJleHAiOjE3NTgzNjY1ODF9.jJTKvw3bvA1lK_oBu1y-fAYdpuR-G8lR7WCyjG2wGis
Content-Type: application/json

{
  "title": "My First Blog Update",
  "content": "This is the content of my blog ddhshjdsjhjsdjsd...",
  "image_blogs": "https://example.com/image.jpg",
  "status": "active"
}

### Delete blog
DELETE http://localhost:4000/api/v1/blogs/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJUcmFuY2hpbmhAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU4MzY0NzgxLCJleHAiOjE3NTgzNjY1ODF9.jJTKvw3bvA1lK_oBu1y-fAYdpuR-G8lR7WCyjG2wGis