export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  INVALID_PARAMS: "INVALID_PARAMS",

  UNAUTHORIZED: "UNAUTHORIZED",

  FORBIDDEN: "FORBIDDEN",

  USER_NOT_FOUND: "USER_NOT_FOUND",

  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  INVALID_TOKEN: "INVALID_TOKEN",

  EXPIRED_TOKEN: "EXPIRED_TOKEN",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  DATABASE_ERROR: "DATABASE_ERROR",

  PERMISSION_DENIED: "PERMISSION_DENIED",

  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",

  PRODUCT_OUT_OF_STOCK: "PRODUCT_OUT_OF_STOCK",

  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",

  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",

  CART_ITEM_NOT_FOUND: "CART_ITEM_NOT_FOUND",

  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",

  PAYMENT_FAILED: "PAYMENT_FAILED",

  BRAND_NOT_FOUND: "BRAND_NOT_FOUND",

  BRAND_ALREADY_EXISTS: "BRAND_ALREADY_EXISTS",

  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",

  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",

  INVALID_SIZE: "INVALID_SIZE",

  INVALID_COLOR: "INVALID_COLOR",

  SIZE_OUT_OF_STOCK: "SIZE_OUT_OF_STOCK",

  COLOR_OUT_OF_STOCK: "COLOR_OUT_OF_STOCK",

  ORDER_ALREADY_SHIPPED: "ORDER_ALREADY_SHIPPED",

  ORDER_CANNOT_BE_CANCELLED: "ORDER_CANNOT_BE_CANCELLED",

  CART_IS_EMPTY: "CART_IS_EMPTY",

  ITEM_ALREADY_IN_CART: "ITEM_ALREADY_IN_CART",
} as const;