import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeAllDb1758020126940 implements MigrationInterface {
    name = 'ChangeAllDb1758020126940'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_30e89257a105eab7648a35c7fce\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_b7213c20c1ecdc6597abc8f1212\``);
        await queryRunner.query(`CREATE TABLE \`shipping_address\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`fullname\` varchar(100) NOT NULL, \`phone_number\` varchar(20) NOT NULL, \`address\` varchar(255) NOT NULL, \`type_address\` enum ('Văn phòng', 'Nhà riêng') NOT NULL DEFAULT 'Nhà riêng', \`is_default\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`colors\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name_color\` varchar(50) NOT NULL, UNIQUE INDEX \`IDX_eeff3e1c95747784bfe72ec04b\` (\`name_color\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_variants\` (\`id\` int NOT NULL AUTO_INCREMENT, \`product_id\` int NOT NULL, \`color_id\` int NULL, \`size\` enum ('S', 'M', 'L', 'XL') NULL, \`price\` decimal(10,2) NOT NULL, \`quantity\` int NOT NULL DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_details\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`product_variant_id\` int NOT NULL, \`quantity\` int NOT NULL, \`price\` decimal(10,2) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`carts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2ec1c94a977b940d85a4f498ae\` (\`user_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_gallery\` (\`id\` int NOT NULL AUTO_INCREMENT, \`image_url\` varchar(255) NOT NULL, \`product_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cancel_order\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`order_detail_id\` int NULL, \`user_id\` int NOT NULL, \`reason\` text NULL, \`quantity\` int NULL, \`refund_amount\` decimal(12,2) NULL, \`status\` enum ('requested', 'approved', 'rejected', 'refunded') NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`processed_at\` timestamp NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`transactions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`order_id\` int NOT NULL, \`transaction_code\` varchar(255) NULL, \`amount\` decimal(12,2) NOT NULL, \`payment_method\` varchar(50) NULL, \`status\` varchar(50) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vouchers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`code\` varchar(50) NOT NULL, \`discount_voucher\` decimal(5,2) NOT NULL, \`expiry_date\` date NOT NULL, \`status\` tinyint NOT NULL DEFAULT 1, \`min_order_value\` decimal(10,2) NULL, \`max_discount\` decimal(10,2) NULL, \`quantity\` int NOT NULL DEFAULT '0', UNIQUE INDEX \`IDX_efc30b2b9169e05e0e1e19d6dd\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`blogs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`content\` longtext NULL, \`image_blogs\` varchar(255) NULL, \`author_id\` int NOT NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`is_email_verified\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`is_phone_verified\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`image_url\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`parent_id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`is_deleted\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`sale_price\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`images\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`sizes\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`colors\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`material\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`gender\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`shipping_fee\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`discount_amount\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`shipping_address\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`notes\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN \`product_id\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN \`selected_size\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN \`selected_color\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`is_verified\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`role\` enum ('ADMIN', 'USER') NOT NULL DEFAULT 'USER'`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`name_category\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`image_category\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`description_category\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`name_product\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`origin_price\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`small_description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`meta_description\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`status\` enum ('active', 'inactive', 'out_of_stock') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`shipping_address_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`note\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`cancel_reason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`voucher_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`cart_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`product_variant_id\` int NOT NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`email\` varchar(150) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone_number\` \`phone_number\` varchar(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_17d1817f241f10a3dbafb169fd\` (\`phone_number\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` enum ('male', 'female') NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`date_of_birth\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`date_of_birth\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_1530a6f15d3c79d1b70be98f2be\``);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`stock_quantity\` \`stock_quantity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand_id\` \`brand_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`total_amount\` \`total_amount\` decimal(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('pending', 'confirmed', 'shipping', 'completed', 'canceled') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`payment_method\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`payment_method\` enum ('COD', 'Momo', 'VNpay') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`payment_status\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`payment_status\` enum ('unpaid', 'paid', 'refunded') NOT NULL DEFAULT 'unpaid'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`quantity\` \`quantity\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`rating\` \`rating\` int(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_1530a6f15d3c79d1b70be98f2be\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` ADD CONSTRAINT \`FK_74b2fbb738d4c71d801a8b974a0\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_67b8be57fc38bda573d2a8513ec\` FOREIGN KEY (\`shipping_address_id\`) REFERENCES \`shipping_address\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_8b91b27dcad5b2bdb13977a176d\` FOREIGN KEY (\`color_id\`) REFERENCES \`colors\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_details\` ADD CONSTRAINT \`FK_3ff3367344edec5de2355a562ee\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_details\` ADD CONSTRAINT \`FK_810213283200298c7966f518467\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carts\` ADD CONSTRAINT \`FK_2ec1c94a977b940d85a4f498aea\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_6385a745d9e12a89b859bb25623\` FOREIGN KEY (\`cart_id\`) REFERENCES \`carts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_de29bab7b2bb3b49c07253275f1\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_gallery\` ADD CONSTRAINT \`FK_4b32447d1fdd03a6bd7a53e42d3\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD CONSTRAINT \`FK_60d7023219b58048989d6993334\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD CONSTRAINT \`FK_d0186460d1e282c0a8e3613f9f0\` FOREIGN KEY (\`order_detail_id\`) REFERENCES \`order_details\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD CONSTRAINT \`FK_04ab7a90e5ddebddb437caf6117\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_3cb0558ed36997f1d9ecc1118e7\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD CONSTRAINT \`FK_b324119dcb71e877cee411f7929\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP FOREIGN KEY \`FK_b324119dcb71e877cee411f7929\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_3cb0558ed36997f1d9ecc1118e7\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP FOREIGN KEY \`FK_04ab7a90e5ddebddb437caf6117\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP FOREIGN KEY \`FK_d0186460d1e282c0a8e3613f9f0\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP FOREIGN KEY \`FK_60d7023219b58048989d6993334\``);
        await queryRunner.query(`ALTER TABLE \`product_gallery\` DROP FOREIGN KEY \`FK_4b32447d1fdd03a6bd7a53e42d3\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_de29bab7b2bb3b49c07253275f1\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_6385a745d9e12a89b859bb25623\``);
        await queryRunner.query(`ALTER TABLE \`carts\` DROP FOREIGN KEY \`FK_2ec1c94a977b940d85a4f498aea\``);
        await queryRunner.query(`ALTER TABLE \`order_details\` DROP FOREIGN KEY \`FK_810213283200298c7966f518467\``);
        await queryRunner.query(`ALTER TABLE \`order_details\` DROP FOREIGN KEY \`FK_3ff3367344edec5de2355a562ee\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_8b91b27dcad5b2bdb13977a176d\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_67b8be57fc38bda573d2a8513ec\``);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` DROP FOREIGN KEY \`FK_74b2fbb738d4c71d801a8b974a0\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_1530a6f15d3c79d1b70be98f2be\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`rating\` \`rating\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`quantity\` \`quantity\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`payment_status\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`payment_status\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`payment_method\``);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`payment_method\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`total_amount\` \`total_amount\` decimal(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`brand_id\` \`brand_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`stock_quantity\` \`stock_quantity\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_1530a6f15d3c79d1b70be98f2be\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`date_of_birth\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`date_of_birth\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`gender\` \`gender\` enum ('male', 'female') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_17d1817f241f10a3dbafb169fd\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`phone_number\` \`phone_number\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN \`product_variant_id\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP COLUMN \`cart_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`voucher_id\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`cancel_reason\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`note\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`shipping_address_id\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`meta_description\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`small_description\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`origin_price\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP COLUMN \`name_product\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`description_category\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`image_category\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`name_category\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`is_verified\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`selected_color\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`selected_size\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`product_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`shipping_address\` json NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`discount_amount\` decimal NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`shipping_fee\` decimal NOT NULL DEFAULT '0.00'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`is_active\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`gender\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`material\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`colors\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`sizes\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`images\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`sale_price\` decimal NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`description\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`is_deleted\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`is_active\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`parent_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`image_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`is_active\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`is_phone_verified\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`is_email_verified\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP TABLE \`blogs\``);
        await queryRunner.query(`DROP INDEX \`IDX_efc30b2b9169e05e0e1e19d6dd\` ON \`vouchers\``);
        await queryRunner.query(`DROP TABLE \`vouchers\``);
        await queryRunner.query(`DROP TABLE \`transactions\``);
        await queryRunner.query(`DROP TABLE \`cancel_order\``);
        await queryRunner.query(`DROP TABLE \`product_gallery\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ec1c94a977b940d85a4f498ae\` ON \`carts\``);
        await queryRunner.query(`DROP TABLE \`carts\``);
        await queryRunner.query(`DROP TABLE \`order_details\``);
        await queryRunner.query(`DROP TABLE \`product_variants\``);
        await queryRunner.query(`DROP INDEX \`IDX_eeff3e1c95747784bfe72ec04b\` ON \`colors\``);
        await queryRunner.query(`DROP TABLE \`colors\``);
        await queryRunner.query(`DROP TABLE \`shipping_address\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_b7213c20c1ecdc6597abc8f1212\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_30e89257a105eab7648a35c7fce\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
