import { MigrationInterface, QueryRunner } from "typeorm";

export class Update170920251758122065831 implements MigrationInterface {
    name = 'Update170920251758122065831'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP FOREIGN KEY \`FK_04ab7a90e5ddebddb437caf6117\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP FOREIGN KEY \`FK_60d7023219b58048989d6993334\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP FOREIGN KEY \`FK_d0186460d1e282c0a8e3613f9f0\``);
        await queryRunner.query(`DROP INDEX \`FK_a2cecd1a3531c0b041e29ba46e1\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_96db6bbbaa6f23cad26871339b\` ON \`brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ec1c94a977b940d85a4f498ae\` ON \`carts\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`role_id\``);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`website\``);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`images\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP COLUMN \`order_id\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP COLUMN \`order_detail_id\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`name_brand\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD UNIQUE INDEX \`IDX_5f0394bc9343da9a06dacc2737\` (\`name_brand\`)`);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`description_brand\` longtext NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` DROP FOREIGN KEY \`FK_74b2fbb738d4c71d801a8b974a0\``);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` CHANGE \`type_address\` \`type_address\` enum ('Văn phòng', 'Nhà riêng', 'Khác') NOT NULL DEFAULT 'Văn phòng'`);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`vouchers\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`vouchers\` ADD \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_67b8be57fc38bda573d2a8513ec\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('pending', 'confirmed', 'shipping', 'completed', 'cancelled') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`payment_method\` \`payment_method\` enum ('COD', 'Momo', 'VNpay') NOT NULL DEFAULT 'COD'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`shipping_address_id\` \`shipping_address_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`size\` \`size\` enum ('S', 'M', 'L', 'XL') NULL DEFAULT 'M'`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`product_id\` \`product_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_details\` DROP FOREIGN KEY \`FK_3ff3367344edec5de2355a562ee\``);
        await queryRunner.query(`ALTER TABLE \`order_details\` DROP FOREIGN KEY \`FK_810213283200298c7966f518467\``);
        await queryRunner.query(`ALTER TABLE \`order_details\` CHANGE \`order_id\` \`order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_details\` CHANGE \`product_variant_id\` \`product_variant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_6385a745d9e12a89b859bb25623\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_de29bab7b2bb3b49c07253275f1\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`cart_id\` \`cart_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`product_variant_id\` \`product_variant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_728447781a30bc3fcfe5c2f1cdf\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_9482e9567d8dcc2bc615981ef44\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`rating\` \`rating\` int(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`user_id\` \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`product_id\` \`product_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`product_gallery\` DROP FOREIGN KEY \`FK_4b32447d1fdd03a6bd7a53e42d3\``);
        await queryRunner.query(`ALTER TABLE \`product_gallery\` CHANGE \`product_id\` \`product_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_3cb0558ed36997f1d9ecc1118e7\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP COLUMN \`payment_method\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD \`payment_method\` enum ('COD', 'Momo', 'VNpay') NOT NULL DEFAULT 'COD'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD \`status\` enum ('pending', 'success', 'failed', 'refunded') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`order_id\` \`order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP FOREIGN KEY \`FK_b324119dcb71e877cee411f7929\``);
        await queryRunner.query(`ALTER TABLE \`blogs\` CHANGE \`author_id\` \`author_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` CHANGE \`status\` \`status\` enum ('requested', 'approved', 'rejected', 'refunded') NOT NULL DEFAULT 'requested'`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` ADD CONSTRAINT \`FK_74b2fbb738d4c71d801a8b974a0\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_67b8be57fc38bda573d2a8513ec\` FOREIGN KEY (\`shipping_address_id\`) REFERENCES \`shipping_address\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_3478da368b5a2f4b7690f44f711\` FOREIGN KEY (\`voucher_id\`) REFERENCES \`vouchers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_details\` ADD CONSTRAINT \`FK_3ff3367344edec5de2355a562ee\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_details\` ADD CONSTRAINT \`FK_810213283200298c7966f518467\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_6385a745d9e12a89b859bb25623\` FOREIGN KEY (\`cart_id\`) REFERENCES \`carts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_de29bab7b2bb3b49c07253275f1\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_728447781a30bc3fcfe5c2f1cdf\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_9482e9567d8dcc2bc615981ef44\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_gallery\` ADD CONSTRAINT \`FK_4b32447d1fdd03a6bd7a53e42d3\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_3cb0558ed36997f1d9ecc1118e7\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD CONSTRAINT \`FK_b324119dcb71e877cee411f7929\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`blogs\` DROP FOREIGN KEY \`FK_b324119dcb71e877cee411f7929\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP FOREIGN KEY \`FK_3cb0558ed36997f1d9ecc1118e7\``);
        await queryRunner.query(`ALTER TABLE \`product_gallery\` DROP FOREIGN KEY \`FK_4b32447d1fdd03a6bd7a53e42d3\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_9482e9567d8dcc2bc615981ef44\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_728447781a30bc3fcfe5c2f1cdf\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_de29bab7b2bb3b49c07253275f1\``);
        await queryRunner.query(`ALTER TABLE \`cart_items\` DROP FOREIGN KEY \`FK_6385a745d9e12a89b859bb25623\``);
        await queryRunner.query(`ALTER TABLE \`order_details\` DROP FOREIGN KEY \`FK_810213283200298c7966f518467\``);
        await queryRunner.query(`ALTER TABLE \`order_details\` DROP FOREIGN KEY \`FK_3ff3367344edec5de2355a562ee\``);
        await queryRunner.query(`ALTER TABLE \`product_variants\` DROP FOREIGN KEY \`FK_6343513e20e2deab45edfce1316\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_3478da368b5a2f4b7690f44f711\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_67b8be57fc38bda573d2a8513ec\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_a922b820eeef29ac1c6800e826a\``);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` DROP FOREIGN KEY \`FK_74b2fbb738d4c71d801a8b974a0\``);
        await queryRunner.query(`ALTER TABLE \`products\` DROP FOREIGN KEY \`FK_9a5f6868c96e0069e699f33e124\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` CHANGE \`status\` \`status\` enum ('requested', 'approved', 'rejected', 'refunded') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` CHANGE \`author_id\` \`author_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`blogs\` ADD CONSTRAINT \`FK_b324119dcb71e877cee411f7929\` FOREIGN KEY (\`author_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transactions\` CHANGE \`order_id\` \`order_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD \`status\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`transactions\` DROP COLUMN \`payment_method\``);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD \`payment_method\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`transactions\` ADD CONSTRAINT \`FK_3cb0558ed36997f1d9ecc1118e7\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_gallery\` CHANGE \`product_id\` \`product_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_gallery\` ADD CONSTRAINT \`FK_4b32447d1fdd03a6bd7a53e42d3\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`product_id\` \`product_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`user_id\` \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` CHANGE \`rating\` \`rating\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_9482e9567d8dcc2bc615981ef44\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_728447781a30bc3fcfe5c2f1cdf\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`product_variant_id\` \`product_variant_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` CHANGE \`cart_id\` \`cart_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_de29bab7b2bb3b49c07253275f1\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cart_items\` ADD CONSTRAINT \`FK_6385a745d9e12a89b859bb25623\` FOREIGN KEY (\`cart_id\`) REFERENCES \`carts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_details\` CHANGE \`product_variant_id\` \`product_variant_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_details\` CHANGE \`order_id\` \`order_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`order_details\` ADD CONSTRAINT \`FK_810213283200298c7966f518467\` FOREIGN KEY (\`product_variant_id\`) REFERENCES \`product_variants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_details\` ADD CONSTRAINT \`FK_3ff3367344edec5de2355a562ee\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`product_id\` \`product_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` CHANGE \`size\` \`size\` enum ('S', 'M', 'L', 'XL') NULL`);
        await queryRunner.query(`ALTER TABLE \`product_variants\` ADD CONSTRAINT \`FK_6343513e20e2deab45edfce1316\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`shipping_address_id\` \`shipping_address_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`user_id\` \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`payment_method\` \`payment_method\` enum ('COD', 'Momo', 'VNpay') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`status\` \`status\` enum ('pending', 'confirmed', 'shipping', 'completed', 'canceled') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_67b8be57fc38bda573d2a8513ec\` FOREIGN KEY (\`shipping_address_id\`) REFERENCES \`shipping_address\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_a922b820eeef29ac1c6800e826a\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vouchers\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`vouchers\` ADD \`status\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` CHANGE \`user_id\` \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` CHANGE \`type_address\` \`type_address\` enum ('Văn phòng', 'Nhà riêng') NOT NULL DEFAULT 'Nhà riêng'`);
        await queryRunner.query(`ALTER TABLE \`shipping_address\` ADD CONSTRAINT \`FK_74b2fbb738d4c71d801a8b974a0\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`products\` CHANGE \`category_id\` \`category_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`products\` ADD CONSTRAINT \`FK_9a5f6868c96e0069e699f33e124\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`description_brand\``);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP INDEX \`IDX_5f0394bc9343da9a06dacc2737\``);
        await queryRunner.query(`ALTER TABLE \`brands\` DROP COLUMN \`name_brand\``);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD \`order_detail_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD \`order_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`is_active\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`images\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`is_active\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`website\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`brands\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`role_id\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_2ec1c94a977b940d85a4f498ae\` ON \`carts\` (\`user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_96db6bbbaa6f23cad26871339b\` ON \`brands\` (\`name\`)`);
        await queryRunner.query(`CREATE INDEX \`FK_a2cecd1a3531c0b041e29ba46e1\` ON \`users\` (\`role_id\`)`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD CONSTRAINT \`FK_d0186460d1e282c0a8e3613f9f0\` FOREIGN KEY (\`order_detail_id\`) REFERENCES \`order_details\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD CONSTRAINT \`FK_60d7023219b58048989d6993334\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cancel_order\` ADD CONSTRAINT \`FK_04ab7a90e5ddebddb437caf6117\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
